### ISSUE TITLE
Thumbnail style view

### ISSUE THREAD

**Issue by rrhyne** [CTOlet/yii2-attachments#59]
I recently created a quick thumbnail style view for the extension I thought you might find useful. If you'd like I can make a pull request for it.

https://gist.github.com/rrhyne/100ebb08ce7b80b5f3ad63d05d69314f

**Comment by Nemmo** [comment]
Very good, could you attach here a screenshot? Thank you!

**Comment by rrhyne** [comment]
<img width="781" alt="screen shot 2017-03-07 at 9 13 31 pm" src="https://cloud.githubusercontent.com/assets/539268/23691048/ff8d087c-037a-11e7-939f-03c9006d8531.png">

**Comment by dmkdesign** [comment]
I have added the Kartik built in initialPreviewConfigs for many file types.  This should help with the Attachments Input preview.
